from __future__ import annotations

from datetime import datetime, timedelta
from typing import Callable

import pandas as pd

DEFAULT_TIME_ZONE = "America/Los_Angeles"


def build_calendar_event_payload(assignment, time_zone: str = DEFAULT_TIME_ZONE) -> dict:
	work_date = pd.to_datetime(assignment.work_date).date()
	start = datetime.combine(work_date, datetime.min.time()).replace(hour=18)
	end = start + timedelta(hours=13)
	resident_name = assignment.resident_name

	return {
		"summary": f"Night Shift - {resident_name}",
		"start": {"dateTime": start.isoformat(), "timeZone": time_zone},
		"end": {"dateTime": end.isoformat(), "timeZone": time_zone},
		"description": (
			"Generated by Residency Scheduler\n"
			f"Resident: {resident_name}\n"
			f"Assignment ID: {assignment.id}"
		),
	}


def build_calendar_events_preview(assignments: pd.DataFrame, time_zone: str = DEFAULT_TIME_ZONE) -> pd.DataFrame:
	"""Return event rows that can be reviewed before publishing."""
	rows: list[dict] = []

	for assignment in assignments.itertuples():
		payload = build_calendar_event_payload(assignment, time_zone=time_zone)

		rows.append(
			{
				"summary": payload["summary"],
				"start": payload["start"]["dateTime"],
				"end": payload["end"]["dateTime"],
				"time_zone": time_zone,
				"description": payload["description"],
				"assignment_id": assignment.id,
				"resident_id": assignment.resident_id,
				"google_event_id": getattr(assignment, "google_event_id", None),
			}
		)

	return pd.DataFrame(rows)


def publish_assignments_to_google_calendar(
	service,
	calendar_id: str,
	assignments: pd.DataFrame,
	save_event_id: Callable[[int, str], None],
	time_zone: str = DEFAULT_TIME_ZONE,
) -> list[dict]:
	"""Upsert assignment events using an authenticated Google Calendar service.

	The UI intentionally does not perform OAuth yet. This function is isolated so
	a configured caller can pass a `googleapiclient.discovery.build("calendar",
	"v3", credentials=...)` service and persist returned event IDs.
	"""
	if not calendar_id:
		raise ValueError("A Google Calendar ID is required before publishing.")

	results: list[dict] = []
	for assignment in assignments.itertuples():
		payload = build_calendar_event_payload(assignment, time_zone=time_zone)
		existing_event_id = getattr(assignment, "google_event_id", None)
		if existing_event_id:
			event = (
				service.events()
				.update(calendarId=calendar_id, eventId=existing_event_id, body=payload)
				.execute()
			)
			action = "updated"
		else:
			event = service.events().insert(calendarId=calendar_id, body=payload).execute()
			action = "created"

		event_id = event["id"]
		save_event_id(int(assignment.id), event_id)
		results.append({"assignment_id": int(assignment.id), "google_event_id": event_id, "action": action})

	return results


def google_calendar_setup_instructions() -> str:
	return (
		"Create a Google Cloud OAuth client with Calendar API enabled, store credentials outside git, "
		"set the target Google Calendar ID on the schedule period, and call "
		"publish_assignments_to_google_calendar with an authenticated calendar v3 service. Existing "
		"google_event_id values are updated; missing IDs create new events and are saved afterward."
	)
