from __future__ import annotations

from datetime import datetime, timedelta

import pandas as pd


def build_calendar_events_preview(assignments: pd.DataFrame) -> pd.DataFrame:
	"""Return the event rows that will eventually be published to Google Calendar."""
	rows: list[dict] = []

	for assignment in assignments.itertuples():
		work_date = pd.to_datetime(assignment.work_date).date()
		start = datetime.combine(work_date, datetime.min.time()).replace(hour=18)
		end = start + timedelta(hours=13)
		resident_name = assignment.resident_name

		rows.append(
			{
				"summary": f"Night Shift - {resident_name}",
				"start": start.isoformat(),
				"end": end.isoformat(),
				"description": f"Generated by Residency Scheduler\nResident: {resident_name}",
				"assignment_id": assignment.id,
				"resident_id": assignment.resident_id,
			}
		)

	return pd.DataFrame(rows)


def publish_assignments_to_google_calendar(*args, **kwargs) -> None:
	"""Placeholder for Google Calendar API integration.

	Planned behavior:
		1. Authenticate with Google OAuth or a service account.
		2. Build one event per assignment.
		3. Create events without an existing google_event_id.
		4. Update events that already have a google_event_id.
		5. Persist event IDs back to the assignments table.
	"""
	raise NotImplementedError("Google Calendar publishing is planned but not implemented yet.")
