from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from typing import Any
from zoneinfo import ZoneInfo

import pandas as pd
from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build

from residency_scheduler import auth
from residency_scheduler.repository import (
	clear_assignment_google_event_ids,
	get_assignments,
	get_period,
	update_assignment_google_event_id,
)

DEFAULT_TIME_ZONE = "America/Los_Angeles"
APP_EXTENDED_PROPERTY = "rs_app=residency_scheduler"


@dataclass(frozen=True)
class PublishResult:
	deleted_count: int
	inserted_count: int
	calendar_id: str


def has_calendar_scopes(auth_session: dict[str, Any]) -> bool:
	return auth.has_calendar_scopes(auth_session)


def build_calendar_authorization_url(config: auth.GoogleOAuthConfig) -> str:
	return auth.build_calendar_authorization_url(config)


def get_calendar_service(auth_session: dict[str, Any]):
	credentials = _credentials_from_auth_session(auth_session)
	return build("calendar", "v3", credentials=credentials, cache_discovery=False)


def list_writable_calendars(auth_session: dict[str, Any], service=None) -> list[dict[str, Any]]:
	service = service or get_calendar_service(auth_session)
	calendars: list[dict[str, Any]] = []
	page_token = None
	while True:
		response = (
			service.calendarList()
			.list(pageToken=page_token, fields="items(id,summary,primary,accessRole),nextPageToken")
			.execute()
		)
		for item in response.get("items", []):
			if item.get("accessRole") in {"owner", "writer"}:
				calendars.append(
					{
						"id": item.get("id", ""),
						"summary": item.get("summary", item.get("id", "")),
						"primary": bool(item.get("primary", False)),
						"accessRole": item.get("accessRole", ""),
					}
				)
		page_token = response.get("nextPageToken")
		if not page_token:
			return calendars


def publish_period_to_calendar(
	period_id: int,
	calendar_id: str,
	auth_session: dict[str, Any],
	service=None,
	time_zone: str = DEFAULT_TIME_ZONE,
) -> PublishResult:
	period = get_period(period_id)
	assignments = get_assignments(period_id)
	if assignments.empty:
		raise ValueError("Generate assignments before publishing to Google Calendar.")

	service = service or get_calendar_service(auth_session)
	existing_event_ids = find_existing_period_events(period_id, calendar_id, auth_session, service=service, time_zone=time_zone)
	deleted_count = _delete_events(service, calendar_id, existing_event_ids)
	clear_assignment_google_event_ids(period_id)

	inserted_count = _insert_assignment_events(service, calendar_id, dict(period), assignments, time_zone=time_zone)

	return PublishResult(deleted_count=deleted_count, inserted_count=inserted_count, calendar_id=calendar_id)


def find_existing_period_events(
	period_id: int,
	calendar_id: str,
	auth_session: dict[str, Any],
	service=None,
	time_zone: str = DEFAULT_TIME_ZONE,
) -> list[str]:
	period = get_period(period_id)
	service = service or get_calendar_service(auth_session)
	return _list_existing_period_event_ids(service, calendar_id, period, time_zone=time_zone)


def build_assignment_event(period: dict[str, Any], assignment, time_zone: str = DEFAULT_TIME_ZONE) -> dict[str, Any]:
	work_date = pd.to_datetime(assignment.work_date).date()
	end_date = work_date + timedelta(days=1)
	year_month = f"{int(period['year'])}-{int(period['month']):02d}"
	assignment_id = str(int(assignment.id))
	resident_name = str(assignment.resident_name)
	return {
		"summary": resident_name,
		"description": (
			"DO NOT EDIT OR DELETE ANY OF THIS INFORMATION\n"
			"Generated by Residency Scheduler\n"
			f"Resident: {resident_name}\n"
			f"Assignment ID: {assignment_id}\n"
			f"Schedule Month: {year_month}"
		),
		"start": {"date": work_date.isoformat()},
		"end": {"date": end_date.isoformat()},
		"extendedProperties": {
			"private": {
				"rs_app": "residency_scheduler",
				"rs_period_id": str(int(period["id"])),
				"rs_year_month": year_month,
				"rs_assignment_id": assignment_id,
			}
		},
	}


def _list_existing_period_event_ids(service, calendar_id: str, period: dict[str, Any], time_zone: str = DEFAULT_TIME_ZONE) -> list[str]:
	time_min, time_max = _month_bounds(period, time_zone=time_zone)
	private_properties = [
		APP_EXTENDED_PROPERTY,
		f"rs_period_id={int(period['id'])}",
		f"rs_year_month={int(period['year'])}-{int(period['month']):02d}",
	]
	event_ids: list[str] = []
	page_token = None
	while True:
		response = (
			service.events()
			.list(
				calendarId=calendar_id,
				timeMin=time_min,
				timeMax=time_max,
				singleEvents=True,
				privateExtendedProperty=private_properties,
				pageToken=page_token,
				fields="items(id),nextPageToken",
			)
			.execute()
		)
		for event in response.get("items", []):
			event_id = event.get("id")
			if event_id:
				event_ids.append(str(event_id))
		page_token = response.get("nextPageToken")
		if not page_token:
			return event_ids


def _delete_events(service, calendar_id: str, event_ids: list[str]) -> int:
	if not event_ids:
		return 0
	if hasattr(service, "new_batch_http_request"):
		errors: list[Exception] = []

		def callback(_request_id, _response, exception):
			if exception is not None:
				errors.append(exception)

		batch = service.new_batch_http_request(callback=callback)
		for event_id in event_ids:
			batch.add(service.events().delete(calendarId=calendar_id, eventId=event_id), request_id=f"delete-{event_id}")
		batch.execute()
		if errors:
			raise RuntimeError(f"Google Calendar delete batch failed: {errors[0]}")
		return len(event_ids)

	for event_id in event_ids:
		service.events().delete(calendarId=calendar_id, eventId=event_id).execute()
	return len(event_ids)


def _insert_assignment_events(service, calendar_id: str, period: dict[str, Any], assignments: pd.DataFrame, time_zone: str) -> int:
	assignment_rows = list(assignments.sort_values(["work_date", "resident_name"]).itertuples())
	if not assignment_rows:
		return 0
	if hasattr(service, "new_batch_http_request"):
		created_event_ids: dict[int, str] = {}
		errors: list[Exception] = []

		def callback(request_id, response, exception):
			if exception is not None:
				errors.append(exception)
				return
			assignment_id = int(str(request_id).removeprefix("insert-"))
			event_id = str((response or {}).get("id") or "")
			if event_id:
				created_event_ids[assignment_id] = event_id

		batch = service.new_batch_http_request(callback=callback)
		for assignment in assignment_rows:
			event = build_assignment_event(period, assignment, time_zone=time_zone)
			batch.add(
				service.events().insert(calendarId=calendar_id, body=event),
				request_id=f"insert-{int(assignment.id)}",
			)
		batch.execute()
		if errors:
			raise RuntimeError(f"Google Calendar insert batch failed: {errors[0]}")
		for assignment_id, event_id in created_event_ids.items():
			update_assignment_google_event_id(assignment_id, event_id)
		return len(assignment_rows)

	for assignment in assignment_rows:
		event = build_assignment_event(period, assignment, time_zone=time_zone)
		created = service.events().insert(calendarId=calendar_id, body=event).execute()
		event_id = str(created.get("id") or "")
		if event_id:
			update_assignment_google_event_id(int(assignment.id), event_id)
	return len(assignment_rows)


def _month_bounds(period: dict[str, Any], time_zone: str = DEFAULT_TIME_ZONE) -> tuple[str, str]:
	tz = ZoneInfo(time_zone)
	year = int(period["year"])
	month = int(period["month"])
	start = datetime(year, month, 1, tzinfo=tz)
	if month == 12:
		end = datetime(year + 1, 1, 1, tzinfo=tz)
	else:
		end = datetime(year, month + 1, 1, tzinfo=tz)
	return start.astimezone(timezone.utc).isoformat(), end.astimezone(timezone.utc).isoformat()


def _credentials_from_auth_session(auth_session: dict[str, Any]) -> Credentials:
	token_payload = dict(auth_session.get("token") or {})
	scopes = sorted(auth._normalise_scopes(token_payload.get("scopes") or auth_session.get("scopes")))
	credentials = Credentials.from_authorized_user_info(token_payload, scopes)
	if credentials.expired and credentials.refresh_token:
		credentials.refresh(Request())
		refreshed_payload = auth._credentials_to_token_payload(credentials)
		profile = dict(auth_session.get("profile") or {})
		config = auth.load_google_oauth_config()
		if profile and config is not None:
			auth.persist_authenticated_user(profile, refreshed_payload, config, True)
		auth_session["token"] = refreshed_payload
		auth_session["scopes"] = list(refreshed_payload.get("scopes") or scopes)
		expires_at = auth._parse_timestamp(refreshed_payload.get("expiry"))
		if expires_at:
			auth_session["expires_at"] = expires_at.isoformat()
	return credentials
