from __future__ import annotations

from io import BytesIO
from datetime import datetime, time, timedelta, timezone
from zipfile import ZIP_DEFLATED, ZipFile
from zoneinfo import ZoneInfo

import pandas as pd

DEFAULT_TIME_ZONE = "America/Los_Angeles"
PRODID = "-//Residency Scheduler//Night Shift Schedule//EN"


def build_fullcalendar_events(assignments: pd.DataFrame) -> list[dict]:
	events: list[dict] = []
	for assignment in assignments.itertuples():
		work_date = pd.to_datetime(assignment.work_date).date()
		events.append(
			{
				"id": str(int(assignment.id)),
				"title": str(assignment.resident_name),
				"start": work_date.isoformat(),
				"end": (work_date + timedelta(days=1)).isoformat(),
				"allDay": True,
				"backgroundColor": str(getattr(assignment, "resident_color", "") or "#2563EB"),
				"borderColor": str(getattr(assignment, "resident_color", "") or "#2563EB"),
				"extendedProps": {
					"assignment_id": int(assignment.id),
					"resident_id": int(assignment.resident_id),
					"resident_color": str(getattr(assignment, "resident_color", "") or ""),
					"source": str(assignment.source),
					"is_locked": bool(int(assignment.is_locked)),
				},
			}
		)
	return events


def build_ical_calendar(assignments: pd.DataFrame, time_zone: str = DEFAULT_TIME_ZONE, calendar_name: str | None = None) -> bytes:
	tz = ZoneInfo(time_zone)
	now = datetime.now(timezone.utc).replace(microsecond=0)
	lines = [
		"BEGIN:VCALENDAR",
		"VERSION:2.0",
		f"PRODID:{PRODID}",
		"CALSCALE:GREGORIAN",
		"METHOD:PUBLISH",
	]
	if calendar_name:
		lines.append(f"X-WR-CALNAME:{_escape_text(calendar_name)}")

	for assignment in assignments.sort_values(["work_date", "resident_name"]).itertuples():
		work_date = pd.to_datetime(assignment.work_date).date()
		start = datetime.combine(work_date, time(hour=18), tzinfo=tz).astimezone(timezone.utc)
		end = (datetime.combine(work_date, time(hour=7), tzinfo=tz) + timedelta(days=1)).astimezone(timezone.utc)
		summary = f"Night Shift - {assignment.resident_name}"
		description = (
			"Generated by Residency Scheduler\n"
			f"Resident: {assignment.resident_name}\n"
			f"Assignment ID: {int(assignment.id)}"
		)

		lines.extend(
			[
				"BEGIN:VEVENT",
				f"UID:residency-scheduler-assignment-{int(assignment.id)}@local",
				f"DTSTAMP:{_format_utc(now)}",
				f"DTSTART:{_format_utc(start)}",
				f"DTEND:{_format_utc(end)}",
				f"SUMMARY:{_escape_text(summary)}",
				f"DESCRIPTION:{_escape_text(description)}",
				"END:VEVENT",
			]
		)

	lines.append("END:VCALENDAR")
	return "\r\n".join(_fold_line(line) for line in lines).encode("utf-8") + b"\r\n"


def build_pgy_ical_zip(assignments: pd.DataFrame, year: int, month: int, time_zone: str = DEFAULT_TIME_ZONE) -> bytes:
	buffer = BytesIO()
	with ZipFile(buffer, "w", compression=ZIP_DEFLATED) as archive:
		pgy_levels = [] if assignments.empty else sorted(assignments["resident_pgy"].dropna().astype(int).unique().tolist())
		for pgy_level in pgy_levels:
			group = assignments[assignments["resident_pgy"].astype(int) == pgy_level]
			calendar_name = f"{int(year)}-{int(month):02d}-PGY{pgy_level}"
			archive.writestr(
				f"{calendar_name}.ics",
				build_ical_calendar(group, time_zone=time_zone, calendar_name=calendar_name),
			)
	return buffer.getvalue()


def _format_utc(value: datetime) -> str:
	return value.astimezone(timezone.utc).strftime("%Y%m%dT%H%M%SZ")


def _escape_text(value: str) -> str:
	return value.replace("\\", "\\\\").replace("\n", "\\n").replace(";", "\\;").replace(",", "\\,")


def _fold_line(line: str) -> str:
	encoded = line.encode("utf-8")
	if len(encoded) <= 75:
		return line

	folded: list[str] = []
	current = ""
	for char in line:
		next_value = current + char
		if len(next_value.encode("utf-8")) > 75:
			folded.append(current)
			current = " " + char
		else:
			current = next_value
	if current:
		folded.append(current)
	return "\r\n".join(folded)
